'use strict';
// Test-only dependency: npm install --prefix .codex/credibility-ui-test playwright --no-save
const { chromium } = require('../.codex/credibility-ui-test/node_modules/playwright');
const assert = require('assert');
const fs = require('fs');
const config = JSON.parse(fs.readFileSync(0, 'utf8'));
(async () => {
    const browser = await chromium.launch({ channel: 'chrome', headless: true });
    try {
        const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
        await context.addCookies([{ name: config.cookieName, value: config.sessionId, domain: '127.0.0.1', path: '/' }]);
        const page = await context.newPage();
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        await page.goto('http://127.0.0.1:18976/html/hrpanel.html', { waitUntil: 'domcontentloaded' });
        await page.locator('a[data-view="ai-insights"]').click({ timeout: 20000 });
        await page.waitForFunction(() => document.querySelectorAll('#cred-review-list input[data-select]').length === 10);
        assert.strictEqual(await page.locator('#cred-review-semester').inputValue(), 'cred-test', 'Current semester must be the default');
        await page.locator('#cred-review-check-all').check();
        assert.strictEqual(await page.locator('#cred-review-list input:checked').count(), 10);
        const boxes = page.locator('#cred-review-list input[data-select]');
        await boxes.nth(0).uncheck(); await boxes.nth(1).uncheck();
        assert.strictEqual(await page.locator('#cred-review-selection').textContent(), '8 selected');
        await page.locator('#cred-review-accept').click();
        assert((await page.locator('#cred-review-confirm-text').textContent()).includes('Accept 8 flagged evaluations?'));
        const confirmBounds = await page.locator('#cred-review-confirm').boundingBox();
        assert(Math.abs(confirmBounds.x + confirmBounds.width / 2 - 720) < 2 && Math.abs(confirmBounds.y + confirmBounds.height / 2 - 500) < 2, 'Confirmation is not centered');
        await page.locator('#cred-review-confirm-submit').click();
        await page.waitForFunction(() => document.getElementById('cred-review-feedback').textContent.includes('8 evaluations accepted.'));
        assert.strictEqual(await page.locator('#cred-review-list input[data-select]').count(), 2);
        await page.reload({ waitUntil: 'domcontentloaded' });
        await page.locator('a[data-view="ai-insights"]').click();
        await page.waitForFunction(() => document.querySelectorAll('#cred-review-list input[data-select]').length === 2);
        await page.locator('#cred-review-list [data-review]').first().click();
        await page.locator('#cred-review-dialog').waitFor({ state: 'visible' });
        assert((await page.locator('#cred-review-detail').textContent()).includes('Behavior data unavailable'));
        assert(!(await page.locator('#cred-review-detail').textContent()).includes('FIXTURE-'));
        await page.locator('#cred-review-individual-reject').click();
        await page.locator('#cred-review-confirm-submit').click();
        await page.waitForFunction(() => document.getElementById('cred-review-feedback').textContent.includes('1 evaluations rejected.'));
        await page.locator('#cred-review-status').selectOption('AUTO_ACCEPTED');
        await page.waitForFunction(() => document.querySelector('#cred-review-list input[data-select]') && document.querySelector('#cred-review-list').textContent.includes('Automatically accepted'));
        await page.locator('#cred-review-list [data-review]').first().click();
        await page.locator('#cred-review-dialog').waitFor({ state: 'visible' });
        assert(await page.locator('#cred-review-individual-reject').isVisible(), 'Current automatic acceptance must allow HR review');
        assert(await page.locator('#cred-review-note').isEnabled(), 'Current automatic acceptance note is locked');
        await page.locator('#cred-review-close').click();
        await page.locator('#cred-review-status').selectOption('ACCEPTED_BY_HR');
        await page.waitForFunction(() => document.querySelector('#cred-review-list [data-review]') && document.querySelector('#cred-review-list').textContent.includes('Accepted by HR'));
        await page.locator('#cred-review-list [data-review]').first().click();
        await page.locator('#cred-review-dialog').waitFor({ state: 'visible' });
        assert(!(await page.locator('#cred-review-individual-accept').isVisible()), 'Completed evaluation showed Accept');
        assert(!(await page.locator('#cred-review-note').isVisible()), 'Completed evaluation showed editable note');
        await page.locator('#cred-review-close').click();
        await page.locator('#cred-review-status').selectOption('all');
        await page.locator('#cred-review-semester').selectOption('cred-submit');
        await page.waitForFunction(() => document.querySelector('#cred-review-list .cred-review-row') && [...document.querySelectorAll('#cred-review-list .cred-review-row')].every(row => row.textContent.includes('cred-submit')));
        assert.strictEqual(await page.locator('#cred-review-list input[data-select]').count(), 0, 'Historical semester offered selection');
        await page.locator('#cred-review-list [data-review]').first().click();
        await page.locator('#cred-review-dialog').waitFor({ state: 'visible' });
        assert(!(await page.locator('#cred-review-individual-reject').isVisible()), 'Historical detail offered Reject');
        assert(await page.locator('#cred-review-note').isDisabled(), 'Historical note is editable');
        await page.locator('#cred-review-close').click();
        await page.locator('#cred-review-semester').selectOption('cred-test');
        await page.locator('#cred-review-status').selectOption('PENDING_HR_REVIEW');
        await page.waitForFunction(() => document.querySelectorAll('#cred-review-list input[data-select]').length === 1);
        await page.screenshot({ path: '.codex/credibility-review-desktop.png', fullPage: false });
        await page.setViewportSize({ width: 390, height: 844 });
        await page.waitForTimeout(500); // Existing drawer/responsive transition must settle before visual QA.
        await page.keyboard.press('Escape');
        await page.locator('#cred-review-heading').scrollIntoViewIfNeeded();
        await page.screenshot({ path: '.codex/credibility-review-mobile.png', fullPage: false });
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'Mobile horizontal overflow');
        assert(await page.locator('#cred-review-section').evaluate(el => el.getBoundingClientRect().height <= 851), 'Credibility review exceeds height limit');
        assert.deepStrictEqual(errors, [], 'Browser errors');
        console.log('PASS: HR page, automatic queue, Check All/uncheck two/Accept eight, reload, individual reject, filters, anonymous N/A detail, desktop/mobile layout.');
    } finally { await browser.close(); }
})().catch(error => { console.error(error.message); process.exitCode = 1; });
